#%RAML 1.0 NamedExample
value:
  ID: 1
  airline: Delta
  flightCode: ER0945
  fromAirportCode: PDX
  toAirportCode: CLE
  departureDate: 2016-Jun-01
  emptySeats: 24
  totalSeats: 350
  price: 450
  planeType: Boeing 747
  transactions:
      - id: 189184844
        idCustomer: 4401
        nameCustomer: Itu Kanda
        amount: 1849
        accountType: personal
        amountUSFormatted: 1,849.00
        region: US
      - id: 189484228
        idCustomer: 1911
        nameCustomer: Jane Sinal
        amount: 1582.48
        accountType: business
        amountEUFormatted: 1.582,48
        region: EU