#%RAML 1.0 NamedExample
value:
  airline: Delta
  flightCode: ER0945
  fromAirportCode: PDX
  toAirportCode: CLE
  departureDate: 2016-Jun-01
  emptySeats: 24
  totalSeats: 350
  price: 450
  planeType: Boeing 747